# Generated by Django 3.2.9 on 2021-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_tag_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='main',
        ),
        migrations.AddField(
            model_name='articletag',
            name='main_tag',
            field=models.BooleanField(default=False, verbose_name='Основной'),
            preserve_default=False,
        ),
    ]
