# Generated by Django 3.2.9 on 2021-12-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211220_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='main_tag',
            new_name='is_main',
        ),
    ]
