# Generated by Django 3.2.9 on 2021-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_main_tag_articletag_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='articles', to='articles.Article', verbose_name='Статьи'),
        ),
    ]
