# Generated by Django 3.2.9 on 2021-12-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20211220_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='articles.Article', verbose_name='Статьи'),
        ),
    ]
