# Generated by Django 3.2.9 on 2021-12-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_tag_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='articles.tag', verbose_name='Разделы')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='articles.article', verbose_name='Разделы')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
